services:
  oshb_database:
    container_name: oshb_database
    image: postgres:16.2-alpine
    env_file:
      - ../.env
    ports:
      - 5431:5432
    volumes:
      - oshb_dbdata:/var/lib/postgresql/data/

volumes:
  oshb_dbdata: