# Generated by Django 5.0.3 on 2024-05-27 14:36

import django.db.models.deletion
import enumfields.fields
import telegram_bot.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram_bot", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DataEntryAuthor",
            new_name="TelegramUser",
        ),
        migrations.CreateModel(
            name="BotStatusChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    enumfields.fields.EnumIntegerField(
                        enum=telegram_bot.enums.UserActionType
                    ),
                ),
                (
                    "chat_type",
                    enumfields.fields.EnumIntegerField(
                        enum=telegram_bot.enums.ChatType
                    ),
                ),
                ("date_time", models.DateTimeField(auto_now_add=True)),
                ("chat_id", models.BigIntegerField()),
                (
                    "initiator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="telegram_bot.telegramuser",
                    ),
                ),
            ],
        ),
    ]
